### PR TITLE
Optionally use system zstd/zlib

### PR DESCRIPTION
**Pull request by jschueller**
Avoid to rebuild an embedded version of zlib/zstd.

### CODE REVIEW

**Comment by disheng222** [comment]
zstd/zlib has been embedded/put as 3rd-party library in SZ package. They are required by default. So, we have to keep them in the SZ package.

**Comment by disheng222** [comment]
To me, it is more stable and safer to keep zstd/zlib in the package instead of additionally downloading/installing them during the installing the SZ code.

**Comment by jschueller** [comment]
Ok, I changed the behavior: it still embeds zlib and zstd, but if these are used only if not found in the system.

**Comment by disheng222** [comment]
Thanks. I tested it: it works fine if the machine already installed zstd beforehand. But if not, it cannot be compiled successfully. See below. It seems that you missed the linking zstd properly.
[  1%] files
[  1%] Built target tags
[  2%] Building C object zstd/CMakeFiles/zstd.dir/decompress/zstd_decompress.c.o
[  3%] Building C object zstd/CMakeFiles/zstd.dir/decompress/huf_decompress.c.o
[  4%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_lazy.c.o
[  5%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstdmt_compress.c.o
[  6%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_double_fast.c.o
[  7%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_fast.c.o
[  8%] Building C object zstd/CMakeFiles/zstd.dir/compress/hist.c.o
[  9%] Building C object zstd/CMakeFiles/zstd.dir/compress/fse_compress.c.o
[ 10%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_opt.c.o
[ 11%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_compress.c.o
[ 12%] Building C object zstd/CMakeFiles/zstd.dir/compress/huf_compress.c.o
[ 13%] Building C object zstd/CMakeFiles/zstd.dir/compress/zstd_ldm.c.o
[ 14%] Building C object zstd/CMakeFiles/zstd.dir/common/xxhash.c.o
[ 15%] Building C object zstd/CMakeFiles/zstd.dir/common/fse_decompress.c.o
[ 16%] Building C object zstd/CMakeFiles/zstd.dir/common/pool.c.o
[ 17%] Building C object zstd/CMakeFiles/zstd.dir/common/zstd_common.c.o
[ 17%] Building C object zstd/CMakeFiles/zstd.dir/common/error_private.c.o
[ 18%] Building C object zstd/CMakeFiles/zstd.dir/common/debug.c.o
[ 19%] Building C object zstd/CMakeFiles/zstd.dir/common/threading.c.o
[ 20%] Building C object zstd/CMakeFiles/zstd.dir/common/entropy_common.c.o
[ 21%] Building C object zstd/CMakeFiles/zstd.dir/deprecated/zbuff_compress.c.o
[ 22%] Building C object zstd/CMakeFiles/zstd.dir/deprecated/zbuff_decompress.c.o
[ 23%] Building C object zstd/CMakeFiles/zstd.dir/deprecated/zbuff_common.c.o
[ 24%] Building C object zstd/CMakeFiles/zstd.dir/dictBuilder/zdict.c.o
[ 25%] Building C object zstd/CMakeFiles/zstd.dir/dictBuilder/divsufsort.c.o
[ 26%] Building C object zstd/CMakeFiles/zstd.dir/dictBuilder/cover.c.o
[ 27%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v03.c.o
[ 28%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v07.c.o
[ 29%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v06.c.o
[ 30%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v01.c.o
[ 31%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v02.c.o
[ 32%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v04.c.o
[ 33%] Building C object zstd/CMakeFiles/zstd.dir/legacy/zstd_v05.c.o
[ 34%] Linking C shared library ../lib/libzstd.so
[ 34%] Built target zstd
[ 34%] Building C object sz/CMakeFiles/SZ.dir/src/ArithmeticCoding.c.o
[ 35%] Building C object sz/CMakeFiles/SZ.dir/src/ByteToolkit.c.o
[ 36%] Building C object sz/CMakeFiles/SZ.dir/src/CacheTable.c.o
[ 37%] Building C object sz/CMakeFiles/SZ.dir/src/CompressElement.c.o
[ 38%] Building C object sz/CMakeFiles/SZ.dir/src/DynamicByteArray.c.o
[ 39%] Building C object sz/CMakeFiles/SZ.dir/src/DynamicDoubleArray.c.o
[ 40%] Building C object sz/CMakeFiles/SZ.dir/src/DynamicFloatArray.c.o
[ 41%] Building C object sz/CMakeFiles/SZ.dir/src/DynamicIntArray.c.o
[ 42%] Building C object sz/CMakeFiles/SZ.dir/src/Huffman.c.o
[ 43%] Building C object sz/CMakeFiles/SZ.dir/src/MultiLevelCacheTable.c.o
[ 44%] Building C object sz/CMakeFiles/SZ.dir/src/MultiLevelCacheTableWideInterval.c.o
[ 45%] Building C object sz/CMakeFiles/SZ.dir/src/TightDataPointStorageD.c.o
[ 46%] Building C object sz/CMakeFiles/SZ.dir/src/TightDataPointStorageF.c.o
[ 47%] Building C object sz/CMakeFiles/SZ.dir/src/TightDataPointStorageI.c.o
[ 48%] Building C object sz/CMakeFiles/SZ.dir/src/TypeManager.c.o
[ 49%] Building C object sz/CMakeFiles/SZ.dir/src/VarSet.c.o
[ 50%] Building C object sz/CMakeFiles/SZ.dir/src/callZlib.c.o
[ 50%] Building C object sz/CMakeFiles/SZ.dir/src/conf.c.o
[ 51%] Building C object sz/CMakeFiles/SZ.dir/src/dataCompression.c.o
[ 52%] Building C object sz/CMakeFiles/SZ.dir/src/dictionary.c.o
[ 53%] Building C object sz/CMakeFiles/SZ.dir/src/iniparser.c.o
[ 54%] Building C object sz/CMakeFiles/SZ.dir/src/pastri.c.o
[ 55%] Building C object sz/CMakeFiles/SZ.dir/src/rw.c.o
[ 56%] Building C object sz/CMakeFiles/SZ.dir/src/rwf.c.o
[ 57%] Building C object sz/CMakeFiles/SZ.dir/src/sz.c.o
[ 58%] Building C object sz/CMakeFiles/SZ.dir/src/sz_double.c.o
[ 59%] Building C object sz/CMakeFiles/SZ.dir/src/sz_double_pwr.c.o
[ 60%] Building C object sz/CMakeFiles/SZ.dir/src/sz_double_ts.c.o
[ 61%] Building C object sz/CMakeFiles/SZ.dir/src/sz_float.c.o
[ 62%] Building C object sz/CMakeFiles/SZ.dir/src/sz_float_pwr.c.o
[ 63%] Building C object sz/CMakeFiles/SZ.dir/src/sz_float_ts.c.o
[ 64%] Building C object sz/CMakeFiles/SZ.dir/src/sz_int16.c.o
[ 65%] Building C object sz/CMakeFiles/SZ.dir/src/sz_int32.c.o
[ 66%] Building C object sz/CMakeFiles/SZ.dir/src/sz_int64.c.o
[ 67%] Building C object sz/CMakeFiles/SZ.dir/src/sz_int8.c.o
[ 67%] Building C object sz/CMakeFiles/SZ.dir/src/sz_omp.c.o
[ 68%] Building C object sz/CMakeFiles/SZ.dir/src/sz_uint16.c.o
[ 69%] Building C object sz/CMakeFiles/SZ.dir/src/sz_uint32.c.o
[ 70%] Building C object sz/CMakeFiles/SZ.dir/src/sz_uint64.c.o
[ 71%] Building C object sz/CMakeFiles/SZ.dir/src/sz_uint8.c.o
[ 72%] Building C object sz/CMakeFiles/SZ.dir/src/szd_double.c.o
[ 73%] Building C object sz/CMakeFiles/SZ.dir/src/szd_double_pwr.c.o
[ 74%] Building C object sz/CMakeFiles/SZ.dir/src/szd_double_ts.c.o
[ 75%] Building C object sz/CMakeFiles/SZ.dir/src/szd_float.c.o
[ 76%] Building C object sz/CMakeFiles/SZ.dir/src/szd_float_pwr.c.o
[ 77%] Building C object sz/CMakeFiles/SZ.dir/src/szd_float_ts.c.o
[ 78%] Building C object sz/CMakeFiles/SZ.dir/src/szd_int16.c.o
[ 79%] Building C object sz/CMakeFiles/SZ.dir/src/szd_int32.c.o
[ 80%] Building C object sz/CMakeFiles/SZ.dir/src/szd_int64.c.o
[ 81%] Building C object sz/CMakeFiles/SZ.dir/src/szd_int8.c.o
[ 82%] Building C object sz/CMakeFiles/SZ.dir/src/szd_uint16.c.o
[ 83%] Building C object sz/CMakeFiles/SZ.dir/src/szd_uint32.c.o
[ 84%] Building C object sz/CMakeFiles/SZ.dir/src/szd_uint64.c.o
[ 84%] Building C object sz/CMakeFiles/SZ.dir/src/szd_uint8.c.o
[ 85%] Building C object sz/CMakeFiles/SZ.dir/src/szf.c.o
[ 86%] Building C object sz/CMakeFiles/SZ.dir/src/utility.c.o
/home/shdi/SZ/sz/src/utility.c:17:18: fatal error: zstd.h: No such file or directory
 #include "zstd.h"
                  ^
compilation terminated.
make[2]: *** [sz/CMakeFiles/SZ.dir/src/utility.c.o] Error 1
make[1]: *** [sz/CMakeFiles/SZ.dir/all] Error 2
make: *** [all] Error 2

Could you fix it?

**Comment by disheng222** [comment]
I fixed the compilation issue by adding "include_directories (${CMAKE_CURRENT_SOURCE_DIR}/zlib)" and "include_directories (${CMAKE_CURRENT_SOURCE_DIR}/zstd)" in CMakeLists.txt.
Thanks for your nice contribution.

**Pull request merged**
